#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed -H 'Cookie: atatusScript=hide; accessAgeDisclaimerPH=1' "$@"
}

declare threads='4' dir='.' cookie_t
declare -r arg0="$(basename "$0")"
declare NOCOMMENTS='0' NOSOCIAL='0'

usage() {
    printf '%s [OPTION...] [DIR]\n' "$(basename "$0")"
    printf "Download, convert to json and save pornhub pages from its sitemap.\n"
    printf "Type of page depends on [-pvmPu] options.\n"
    printf "Pages will be saved in files named by their sha256 hash of urls and placed in DIR.\n\n"
    printf "Options:\n"
    printf "  -t NUM\tset number of used threads, by default set to 4\n"
    printf "  -p\t\tpornstars\n"
    printf "  -v\t\tvideos\n"
    printf "  -m\t\tmodels\n"
    printf "  -P\t\tplaylists\n"
    printf "  -u FILE\tget users from urls in FILE\n"
    printf "  -C\t\tdo not seek comments\n"
    printf "  -S\t\tdo not seek social things like: subscribers, subscriptions, friends\n"
    printf "  -h\t\tshow help\n"
}

declare jq_comments='map(split("\t") | {
            ("name"):.[4],
            ("userid"):.[2],
            ("user_link"):.[1],
            ("verified"):.[5],
            ("avatar"):.[3],
            ("nested"):.[0],
            ("date"): (
                (.[6] | split(" ")) as $l |
                (if (($l | length) > 1) then
                    ($l[0] | tonumber) as $n |
                    if ($l[1] | test("minut")) then now-($n*60)
                    elif ($l[1] | test("hour")) then now-($n*3600)
                    elif ($l[1] | test("day")) then now-($n*86400)
                    elif ($l[1] | test("week")) then now-($n*604800)
                    elif ($l[1] | test("month")) then now-($n*2635200)
                    elif ($l[1] | test("year")) then now-($n*31557600)
                    else (now-$n) end
                else
                    if ($l[0] | test("Yesterday")) then now-86400
                    else now end
                end) | todate
            ),
            ("message"):.[7],
            ("likes"):.[8],
            ("id"):.[9]
        })'

declare jq_achievements='split("\t")[:-1]'
declare jq_users='split("\t") | map(split("\"") | {
        ("id"):.[0],
        ("name"):.[1],
        ("link"):.[2]
    })'
declare jq_channels='split("\t")[:-1] | map(split("\"") | {
        ("link"):.[0],
        ("name"):.[1]
    })'
declare jq_gifphotos='split("\t") | map(split("\"") | {
        ("name"):.[0],
        ("list"):(.[1] | split(",")[:-1])
    })'

get_comments() {
    local t url page view_responses='-data-comment-key'
    [ "$NOCOMMENTS" -eq '1' ] && { echo; return; }

    t="$(reliq 'div #cmtContent | "%i\n"' < /dev/stdin)"

    {
    while :
    do
        reliq 'div .topCommentBlock |  "<el><lvl>%l</lvl>%C</el>\n"' <<< "$t"
        for i in $(reliq 'button data-ajax-url data-page-num data-comment-key | "https://pornhub.com%(data-ajax-url)v\n" / sed "s/&amp;/&/g"' <<< "$t")
        do
            echo "$i" >&2
            ucurl -L -b "$cookie_t" "$i" | tr -d '\t\n\r' | reliq 'div .topCommentBlock [2:] | "<el><lvl>99</lvl>%C<forcomment>'"$(sed 's/.*&commentId=//;s/&.*//' <<< "$i")"'</forcomment></el>\n"'
        done
        url="$(reliq 'button data-ajax-url data-page-num -data-comment-key | "https://pornhub.com%(data-ajax-url)v\n" / sed "s/&amp;/&/g"' <<< "$t")"
        [ -z "$url" ] && break
        echo "$url" >&2
        page="$(reliq 'button data-ajax-url data-page-num -data-comment-key | "%(data-page-num)v\n"' <<< "$t")"
        url="$url&page=$((++page))&isLoadMoreAjax=1"
        t="$(ucurl -L -b "$cookie_t" "$url" | tr -d '\t\n\r')"
    done
    } | reliq '
        el m@v>"[[dateAdd]]" l@[0]; {
            . lvl | "%i\n",
            . a .userLink href | "%(href)v\n",
            . a .userLink data-userid | "%(data-userid)v\n",
            . img .commentAvatarImg src | "%(src)v\n",
            . a .usernameLink | "%i\n",
            . span .verified-icon [0] | "verified\n",
            . div .date | "%i\n",
            . div .commentMessage; span c@[0] [0] | "%i\n",
            . span .voteTotal | "%i\n",
            . div .E>Reply[0-9]+ | "%(class)v\n" / sed "s/.*Reply//;s/ .*//",
            . forcomment | "%i\n"
        } | tr "\n" "\t" echo "" "\n"' | awk -F '\t' '
    {
        if (!minlvl)
            minlvl = $1;
        if ($11 == "") {
            x[gx++] = $0;
        } else {
            y[gy++] = $0;
        }
    }

    function print_fields(f) {
        print ((f[1] > minlvl) ? "true" : "false"),f[2], f[3], f[4], f[5], (f[6] ? "true" : "false"), f[7], f[8], f[9], f[10]
    }

    END {
        OFS="\t"
        for (i = 0; i < gx; i++) {
            split(x[i],fi)
            print_fields(fi)
            if (fi[1] > minlvl)
                continue
            id=fi[10]
            split(x[++i],fi)
            if (i >= gx)
                continue
            while (fi[1] > minlvl && i < gx) {
                print_fields(fi)
                split(x[++i],fi)
            }
            if (fi[1] <= minlvl)
                i--
            for (j = 0; j < gy; j++) {
                split(y[j],fi)
                if (fi[11] == id)
                    print_fields(fi)
            }
        }
    }'
}

get_achievements() {
    ucurl -b "$cookie_t" "$1" | tr -d '\n\t\r' | reliq 'ul .achievementsUl; div .achievementTitle; * c@[0] | "%i\t"' < /dev/stdin
}

pages_button() {
    echo "$1" >&2
    local last current='1' t="$(ucurl "$1" | tr -d '\n\t\r')" sort command="$(</dev/stdin)"
    last="$(reliq 'button #moreDataBtn onclick | "%(onclick)v\n" / sed "s/.*('\''[^'\'']*'\'', '\''//;s/'\'',.*//"' <<< "$t")"
    [ -z "$last" ] && last='1'

    [ "$#" -gt '2' ] && sort="o=$3&"

    t="$(reliq 'ul #moreData | "%i\n"' <<< "$t")"
    while :
    do
        eval "$command"
        return
        ((current++))
        [ "$current" -gt "$last" ] && break
        echo "$1/ajax?${sort}page=$current" >&2
        t="$(ucurl -b "$cookie_t" -X POST -H 'X-Requested-With: XMLHttpRequest' "$1/ajax?${sort}page=$current" | tr -d '\n\t\r')"
    done
}

get_users() {
    echo 'paste -d '\''"'\'' <(reliq '\''div data-type=user data-userid m@"class=\"usernameLink\"" | "%(data-userid)v\n"'\'' <<< "$t") <(reliq '\''a .usernameLink title | "%(title)v\n"'\'' <<< "$t") <(reliq '\''a .usernameLink href | "%(href)v\n"'\'' <<< "$t") ' | pages_button "$@" | paste -sd '\t' #id name link
}

get_channels() {
    echo 'reliq '\''div .wtitle; a href | "%(href)v\"%i\t"'\'' <<< "$t"' | pages_button "$@" #link name
}

get_pornstars_model() { #jq_channels
    echo 'reliq '\''li; a .js-mxp | "%(href)v\"%i\t"'\'' <<< "$t"' | pages_button "$@" #link name
}

get_pornstars_user() { #jq_channels
    echo 'reliq '\''li; a class="" href | "%(href)v\"%i\t"'\'' <<< "$t"' | pages_button "$@" #link name
}

get_gifphotos() {
    for i in $(ucurl -b "$cookie_t" "$1" | tr -d '\n\t\r' | reliq 'div .section_header; a -.seeAllButton href | "https://www.pornhub.com%(href)v\n"')
    do
        printf '%s"' "$(sed 's/.*\///' <<< "$i")"
        echo 'sed '\''s#/gif/#g#g;s#/photo/#p#g;s#/album/#a#g'\'' <<< "$t" | reliq '\''li id; a href | "%(href)v,"'\''' | pages_button "$i"
        echo
    done | paste -sd '\t'
}

get_videos() { #jq_gifphotos
    for i in $(ucurl -b "$cookie_t" "$1" | tr -d '\n\t\r' | reliq 'div .section_header; a -.seeAllButton -data-title href | "https://www.pornhub.com%(href)v\n"')
    do
        printf '%s"' "$(sed 's/.*\///' <<< "$i")"
        echo 'sed '\''s/\/view_video.php?viewkey=//g'\'' <<< "$t" | reliq '\''li id; * .title; a title href | "%(href)v,"'\''' | pages_button "$i"
        echo
    done | paste -sd '\t'
}

get_costars() { #jq_costars
    local t next="$1"

    while :
    do
        echo "$next" >&2
        t="$(ucurl -b "$cookie_t" "$next" | tr -d '\n\t\r')"
        reliq 'a data-mxptype=Pornstar data-mxptext href m@v>"<img" | "%(href)v\"%(data-mxptext)v\t"' <<< "$t" #link name
        return

        next="$(reliq 'li .page_next; a href | "https://www.pornhub.com%(href)v\n"' <<< "$t")"
        [ -z "$next" ] && exit
    done
}

get_v_json() {
    local -r url="$1"
    local -r t2="$(ucurl -c "$cookie_t" "$1")"
    local -r t="$(tr -d '\n\t\r' <<< "$t2")"
    local _tmp1 _tmp2 _tmp3
    #featured on
    {
    echo "${1##*viewkey=}" #id
    reliq 'script type="application/ld+json" | "%i"' <<< "$t" | jq -r '"\(.uploadDate)\n\(.author)\n\(.interactionStatistic[0].userInteractionCount | sub(",";"";"g"))\n\(.interactionStatistic[1].userInteractionCount | sub(",";"";"g"))"' #date author views likes
    reliq 'script | "%i\n" / sed "/var flashvars_[0-9]+ = \{/{s/.*var flashvars_[0-9]+ = //; s/;$//; p;q}" "nE"' <<< "$t2" | jq -r '"\(.video_duration)\n\(.actionTags)\n\(.image_url)\n\(.video_title)\n\(.hotspots)\n\(.defaultQuality)\n\(.thumbs)"' #duration actions thumbnail title hotspots qualities timelines
    reliq '
        . span .votesDown data-rating | "%(data-rating)v\n",
        . div .userInfo; a .bolded href | "%(href)v\n",
        . div .userInfo; div data-userid | "%(data-userid)v\n",
        . span .favoritesCounter | "%i\n",
        . a .pstar-list-btn href | "%(href)v\t" / echo "" "\n",
        . div .categoriesWrapper; a .item | "%i\t" / echo "" "\n",
        . div .tagsWrapper; a .item | "%i\t" / echo "" "\n",
        . div .relatedSearchTermsContainer; a .relatedSearchTermsSuggestion | "%i\t" / echo "" "\n",
        . div .productionWrapper; a .item | "%i\t" / echo "" "\n"
    ' <<< "$t"
    echo "$(get_comments <<< "$t")"
    } | jq -RnMcs '
        (inputs | split("\n"))[:-1] as $lines |
        .["id"]=$lines[0] |
        .["date"]=$lines[1] |
        .["author"]=$lines[2] |
        .["views"]=$lines[3] |
        .["likes"]=$lines[4] |
        .["duration"]=$lines[5] |
        .["actions"]=($lines[6] | split(",") | map(split(":") | {
            ("action"):.[0],
            ("time"):.[1]
        })) |
        .["thumbnail"]=$lines[7] |
        .["title"]=$lines[8] |
        .["hotspots"]=($lines[9] | fromjson) |
        .["qualities"]=($lines[10] | fromjson) |
        .["timelines"]=($lines[11] | fromjson) |
        .["dlikes"]=$lines[12] |
        .["author_link"]=$lines[13] |
        .["authorid"]=$lines[14] |
        .["fav_count"]=$lines[15] |
        .["cast"]=($lines[16] | split("\t"))[:-1] |
        .["categories"]=($lines[17] | split("\t"))[:-1] |
        .["tags"]=($lines[18] | split("\t"))[:-1] |
        .["attributes"]=($lines[19] | split("\t"))[:-1] |
        .["production"]=($lines[20] | split("\t"))[:-1] |
        .["comments"]=(if $lines[21] == "" then [] else $lines[21:] | '"$jq_comments"' end)'
}

get_p_json() {
    local -r t="$(ucurl -c "$cookie_t" "$1" | tr -d '\n\t\r\a')"
    local _tmp1 t2
    {
    echo "${1#https://www.pornhub.com}" #id
    _tmp1="$(reliq 'div .name; h1 |  "%i\n"' <<< "$t")"
    echo "${_tmp1// /}" #name
    if [ -n "$(reliq 'div .badge-username; i .verifiedIcon' <<< "$t")" ]
    then
        echo 'true'
    else
        echo 'false'
    fi #verified
    if [ -n "$(reliq 'div .badge-username; span .b>trophyPornStar' <<< "$t")" ]
    then
        echo 'true'
    else
        echo 'false'
    fi #winner
    echo "$(reliq 'img #coverPictureDefault | "%(src)v\n"' <<< "$t")" #cover
    _tmp1="$(reliq 'img #getAvatar | "%(src)v\n"' <<< "$t")"
    [ -z "$_tmp1" ] && _tmp1="$(reliq 'div .thumbImage; img src | "%(src)v\n"' <<< "$t")"
    echo "$_tmp1" #avatar
    _tmp1="$(reliq 'div .a>videoViews data-title | "%(data-title)v\n"' <<< "$t")"
    echo "${_tmp1//[^0-9]/}" #views
    _tmp1="$(reliq 'div  data-title=b>"Subscribers: " | "%(data-title)v\n"' <<< "$t")"
    [ -z "$_tmp1" ] && _tmp1="$(reliq 'div .infoBox; span -class m@B>"[0-9]" | "%i\n"' <<< "$t")"
    echo "${_tmp1//[^0-9]/}" #subscribers_count
    echo "$(reliq 'div .rankingInfo; span .big | "%i\n" / sed "s/ //g; s/<[^>]*>//g"' <<< "$t")" #current_rank #weekly_rank #monthly_rank #last_month_rank #yearly_rank
    echo "$(reliq 'div .infoPiece | "%i\n" / sed "s/<[^>]*>/\n/g; s/  */ /g" sed "s/^ *//; s/ *$//; /^$/d" sed ":x; $!{N;s/:\n/\a/; s/  */ /g; N; s/\n/\t/; bx}"' <<< "$t")" #info_pieces
    echo "$(reliq 'ul .socialList; a href | "%(href)v\t"' <<< "$t")" #social
    _tmp1="$(reliq 'div itemprop=description | "%i\n"' <<< "$t")"
    [ -z "$_tmp1" ] && _tmp1="$(reliq 'div class="text longBio js-bioText" | "%i\n"' <<< "$t")"
    [ -z "$_tmp1" ] && _tmp1="$(reliq 'div class=b>"content "; div -class | "%i\n"' <<< "$t")"
    echo "$(tr '\n' '\t' <<< "$_tmp1" | sed 's/<\/div>.*//')" #desc
    echo "$(reliq 'div .featuredIn; a href | "%(href)v\t"' <<< "$t")" #featured

    t2="$(ucurl -b "$cookie_t" "$1/about" | tr -d '\n\t\r')"
    if [ -n "$(reliq 'li #E>"(pornstar|profile)About" | "%l\n"' <<< "$t")" ]
    then
        local a

        for i in 'achievements`achievements`all-achievements``' 'subscribers`users`subscribers`recent_subscribers`' 'subscriptions`users`subscriptions`recent_subscribers`' 'pornstar-subscriptions`pornstars_model`pornstar-subscriptions`recent_subscribers`' 'channel-subscriptions`channels``recent_subscribers`' 'friends`users`friends`recent_friendships`' 'costars`costars`costars``'
        do
            mapfile -t -d '`' a <<< "$i"
            if [ "$NOSOCIAL" -ne "1" -a -n "$(reliq 'div .sectionHeader; a -class=seeAll href=e>"/'"${a[0]}"'" | "%l\n"' <<< "$t2")" ]
            then
                echo "$(get_${a[1]} "$1/${a[2]}" "${a[3]}")"
            else
                echo
            fi
        done
    else
        printf '\n\n\n\n\n\n\n'
    fi #achievements subscribers subscriptions pornstar_subscriptions channel_subscriptions friends costars

    t2="$(reliq 'li #E>"(pornstar|profile)Photos" m@E>"(GIFs|Photos)"; * c@[0]' <<< "$t")"
    if [ -n "$t2" ]
    then
        echo "$(grep -q 'GIFs' <<< "$t2" && get_gifphotos "$1/gifs")"
        echo "$(grep -q 'Photos' <<< "$t2" && get_gifphotos "$1/photos")"
    else
        printf '\n\n'
    fi #gifs photos

    if [ "$NOCOMMENTS" -ne '1' -a -n "$(reliq 'li #E>"(pornstar|profile)Photos" m@">Comments<" | "%l\n"' <<< "$t")" ]
    then
        echo "$(ucurl -b "$cookie_t" "$1/comments" | tr -d '\n\t\r' | get_comments)"
    else
        echo
    fi #comments
    } | jq -RnMcs '
        (inputs | split("\n"))[:-1] as $lines |
        .["id"]=$lines[0] |
        .["name"]=$lines[1] |
        .["verified"]=$lines[2] |
        .["winner"]=$lines[3] |
        .["cover"]=$lines[4] |
        .["avatar"]=$lines[5] |
        .["views"]=$lines[6] |
        .["subscribers_count"]=$lines[7] |
        .["current_rank"]=$lines[8] |
        .["weekly_rank"]=$lines[9] |
        .["monthly_rank"]=$lines[10] |
        .["last_month_rank"]=$lines[11] |
        .["yearly_rank"]=$lines[12] |
        .["info_pieces"]=($lines[13] | split("\t") | map(split("") | {("key"):.[0],("value"):.[1]})) |
        .["social"]=(($lines[14] | split("\t"))[:-1]) |
        .["desc"]=$lines[15] |
        .["featured"]=(($lines[16] | split("\t"))[:-1]) |
        .["achievements"]=($lines[17] | '"$jq_achievements"') |
        .["subscribers"]=($lines[18] | '"$jq_users"') |
        .["subscriptions"]=($lines[19] | '"$jq_users"') |
        .["pornstar_subscriptions"]=($lines[20] | '"$jq_channels"') |
        .["channel_subscriptions"]=($lines[21] | '"$jq_channels"') |
        .["friends"]=($lines[22] | '"$jq_users"') |
        .["costars"]=($lines[23] | '"$jq_channels"') |
        .["gifs"]=($lines[24] | '"$jq_gifphotos"') |
        .["photos"]=($lines[25] | '"$jq_gifphotos"') |
        .["comments"]=if $lines[26] == "" then [] else ($lines[26:] | '"$jq_comments"') end'
}

get_u_json() {
    local -r link="${1%/}"
    local -r t="$(ucurl -c "$cookie_t" "$link" | tr -d '\n\t\r\a')"
    local _tmp1 t2
    {
    echo "${1#https://www.pornhub.com}" #link
    echo "$(reliq 'div .profileUserName; a title | "%(title)v\n"' <<< "$t")" #name
    echo "$(reliq 'div .addFriendButton data-button-id | "%(data-button-id)v\n" / sed "s/^friend_//"' <<< "$t")" #id
    echo "$(reliq 'img #coverPictureDefault | "%(src)v\n"' <<< "$t")" #cover
    _tmp1="$(reliq 'img #getAvatar | "%(src)v\n"' <<< "$t")"
    [ -z "$_tmp1" ] && _tmp1="$(reliq 'div .thumbImage; img src | "%(src)v\n"' <<< "$t")"
    echo "$_tmp1" #avatar
    echo "$(reliq 'div .profileInfo; B>d[td] | "%i\n" / sed ":x; N;s/:\n/\a/; $!{N;s/\n/\t/;bx}"' <<< "$t")" #info_pieces
    echo "$(reliq 'div .profileInfo; p | "%i\n"' <<< "$t")" #desc

    local -a a
    for i in 'myachievements`achievements`achievements``' 'subscribers`users`subscribers`recent_subscribers`' 'subscriptions`users`subscriptions`recent_subscribers`' 'pornstar_subscriptions`pornstars_user`pornstar_subscriptions`recent_subscribers`' 'channel_subscriptions`channels`channel_subscriptions``' 'friends`users`friends`recent_friendships`'
    do
        mapfile -t -d '`' a <<< "$i"
        if [ -n "$(reliq 'div .sectionTitle; a href=e>"/'"${a[0]}"'" m@v>"seeAll" | "%l\n"' <<< "$t")" ]
        then
            echo "$(get_${a[1]} "$link/${a[2]}" "${a[3]}")"
        else
            echo
        fi
    done #achievements subscribers subscriptions pornstar_subscriptions channel_subscriptions friends

    t2="$(reliq 'li #E>"(pornstar|profile)Photos" m@E>"(GIFs|Photos)"; * c@[0]' <<< "$t")"
    if [ -n "$t2" ]
    then
        echo "$(grep -q 'GIFs' <<< "$t2" && get_gifphotos "$link/gifs")"
        echo "$(grep -q 'Photos' <<< "$t2" && get_gifphotos "$link/photos")"
    else
        printf '\n\n'
    fi #gifs photos

    echo "$(get_videos "$link/videos")" #videos

    } | jq -RnMc '
        .["link"]=input |
        .["name"]=input |
        .["id"]=input |
        .["cover"]=input |
        .["avatar"]=input |
        .["info_pieces"]=(input | split("\t") | map(split("") | {("key"):.[0],("value"):.[1]})) |
        .["desc"]=input |
        .["achievements"]=(input | '"$jq_achievements"') |
        .["subscribers"]=(input | '"$jq_users"') |
        .["subscriptions"]=(input | '"$jq_users"') |
        .["pornstar_subscriptions"]=(input | '"$jq_channels"') |
        .["channel_subscriptions"]=(input | '"$jq_channels"') |
        .["friends"]=(input | '"$jq_users"') |
        .["gifs"]=(input | '"$jq_gifphotos"') |
        .["photos"]=(input | '"$jq_gifphotos"') |
        .["videos"]=(input | '"$jq_gifphotos"')'
}

get_P_json() {
    local -r t="$(ucurl -c "$cookie_t" "$1")"
    local _tmp1 _tmp2 _tmp3
    {
    sed -n '/^        PLAYLIST_VIEW = {/{ s/^        PLAYLIST_VIEW = //; s/;$//; p;q}' <<< "$t" | jq -r '(.description | split("\n") | join("\t")) as $l | "\(.title)\n\($l)\n\(.user_id)\n\(.id)\n\(.date_added)\n\(.date_updated)\n\(.favorite_count)"' #title #desc #userid #id #added #updated #fav_count
    reliq '
        . div #js-aboutPlaylistTabView; div .usernameWrap; a | "%i\n",
        . div #js-aboutPlaylistTabView; div .usernameWrap; a href | "%(href)v\n",
        . div .views; span .count | "%i\n" / tr ",",
        . div .votes-count-container; span .votesUp | "%i\n",
        . div .votes-count-container; span .votesDown | "%i\n",
        . div #tagSection; a .item |  "%i\t" / echo "" "\n"
    ' <<< "$t"
    _tmp2="$(sed -n '/^        var itemsCount = /{s/^.* = //;s/ .*//;p;q}' <<< "$t")"
    _tmp1="$(sed -n '/^        var lazyloadUrl = /{s/^        var lazyloadUrl = "/https:\/\/pornhub\.com/; s/";$//; p;q}' <<< "$t")"
    reliq 'ul #videoPlaylist; li data-video-vkey |  "%(data-video-vkey)v\t"' <<< "$t"
    for ((i=2; i <= ((_tmp2-36)/40)+1; i++))
    do
        ucurl -b "$cookie_t" "$_tmp1&page=$i" | reliq 'li data-video-vkey |  "%(data-video-vkey)v\t"'
    done #vids
    echo
    echo "$(tr -d '\n\r\t'  <<< "$t" | get_comments)" #comments
    } | jq -RnMcs '
        (inputs | split("\n"))[:-1] as $lines |
        .["title"]=$lines[0] |
        .["desc"]=($lines[1] | split("\t") | join("\n")) |
        .["authorid"]=$lines[2] |
        .["id"]=$lines[3] |
        .["added"]=$lines[4] |
        .["uploaded"]=$lines[5] |
        .["fav_count"]=$lines[6] |
        .["author"]=$lines[7] |
        .["author_link"]=$lines[8] |
        .["views"]=$lines[9] |
        .["likes"]=$lines[10] |
        .["dlikes"]=$lines[11] |
        .["tags"]=($lines[12] | split("\t"))[:-1] |
        .["vids"]=($lines[13] | split("\t"))[:-1] |
        .["comments"]=(if $lines[14] == "" then [] else $lines[14:] | '"$jq_comments"' end)'
}

[ "$#" -eq '0' ] && { usage >&2; exit 1; }

while [ "$#" -gt 0 ]
do
    case "$1" in
        -t) threads="$2"; shift;;
        -p) pattern='pornstars'; func='get_p_json';;
        -v) pattern='g_vids'; func='get_v_json';;
        -m) pattern='models'; func='get_p_json';;
        -P) pattern='playlists'; func='get_P_json';;
        -u) pattern="$(realpath "$2")"; func='get_u_json'; shift;;
        -C) NOCOMMENTS='1';;
        -S) NOSOCIAL='1';;
        -h) usage; exit 0;;
        -*) printf '%s: invalid argument -- %s\n' "$(basename "$0")" "$1" >&2; exit 1;;
        *) dir="$1";;
    esac
    shift
done

[ -z "$pattern" ] && { printf '%s: No option specified the type of pages\n' "$(basename "$0")" >&2; exit 1; }
cd "$dir" || exit 1

cookie_t="$(mktemp)"
trap 'rm "$cookie_t"; exit' EXIT

if [ "$func" = "get_u_json" ]
then
    [ -f "$pattern" ] || { printf '%s: "%s" is not a file\n' "$arg0" "$pattern" >&2; exit 1; }
    while read -r c
    do
        [ "$(jobs | wc -l)" -gt "$threads" ] && wait %%
        out="$(sha256sum <<< "$c")"
        out="${out%  *}"
        [ -e "$out" ] && continue
        echo "$c"
        get_u_json "$c" > "$out" &
    done < "$pattern"
    exit
fi

for i in $(ucurl 'https://www.pornhub.com/sitemaps.xml' | reliq 'loc m@B>"/sitemap_'"$pattern"'[0-9]*\.xml" | "%i\n"')
do
    for j in $(ucurl "$i" | reliq 'loc | "%i\n"')
    do
        [ "$(jobs | wc -l)" -gt "$threads" ] && wait %%
        rh="$(sha256sum <<< "$j")"
        rn="${rh%  *}"
        [ -e "$rn" ] && continue
        echo "$j"
        "$func" "$j" > "$rn" &
    done
done

wait

#tr -d '\0'
#jq -r '.comments[].user_link' pornhub-videos.json | grep '/users/'
#jq -r '.author_link' pornhub-playlists.json | grep '/users/'
#jq -r  '.subscribers[].link , .subscriptions[].link , .friends[].link  , .comments[].user_link' pornhub-models.json pornhub-pornstars.json | grep '/users/'
#sed -i 's#^#https://www.pornhub.com#' pornhub-userlist
